# Change these first
owner: pulibrary # Your GitHub username
repo: uptime # Your Github repository name

user-agent: pulibrary

# Add your sites here
sites:
  - name: Library Website
    url: https://library.princeton.edu
  - name: Library Catalog
    url: https://catalog.princeton.edu
  - name: Maps Website
    url: https://maps.princeton.edu
  - name: Figgy
    url: https://figgy.princeton.edu
  - name: Research Data
    url: https://researchdata.princeton.edu
  - name: Cicognara
    url: https://cicognara.org
  - name: DPUL
    url: https://dpul.princeton.edu
  - name: Dataspace
    url: https://dataspace.princeton.edu
  - name: OAR
    url: https://oar.princeton.edu
  - name: Bibdata
    url: https://bibdata.princeton.edu
  - name: Confluence
    url: https://lib-confluence.princeton.edu
  - name: Secret Site
    url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: pulibrary.github.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This status page uses **real-time** data from our [Github repository](https://github.com/pulibrary/uptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
